# Generated by Django 5.0.2 on 2024-02-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('theme_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField()),
                ('phone_no', models.IntegerField(max_length=10)),
                ('coins', models.IntegerField(default=100)),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatifyApp.themes')),
            ],
        ),
    ]
