# Generated by Django 5.0.2 on 2024-02-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='theme_id',
        ),
    ]
