# Generated by Django 5.0.2 on 2024-02-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0002_remove_userinfo_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='theme_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatifyApp.themes'),
        ),
    ]
