# Generated by Django 5.0.2 on 2024-03-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
