# Generated by Django 5.0.2 on 2024-03-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0008_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='latsname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phoneno',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
