# Generated by Django 5.0.2 on 2024-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0011_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
