# Generated by Django 5.0.2 on 2024-03-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0016_groups_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_list',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_list_friend_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend_list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_list_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('msg_time', models.TimeField()),
                ('msg_date', models.DateField()),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver_id', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_id', to='chatifyApp.groups')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_sender_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_group_id', to='chatifyApp.groups')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'group_id')},
            },
        ),
    ]
