# Generated by Django 5.0.2 on 2024-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0017_alter_friend_list_friend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='friend_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
