# Generated by Django 5.0.2 on 2024-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0018_friend_list_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='msg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='msg_time',
            field=models.TimeField(null=True),
        ),
    ]
