# Generated by Django 5.0.2 on 2024-03-28 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0023_alter_chats_receiver_id_alter_chats_sender_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chats',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themes',
            name='theme_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
