# Generated by Django 5.0.2 on 2024-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatifyApp', '0025_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='last_chat_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='friend_list',
            name='last_chat_time',
            field=models.TimeField(null=True),
        ),
    ]
